import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdirSync } from 'node:fs';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const out = process.env.RIND_SCREENSHOTS || 'screenshots/rind';
mkdirSync(out, { recursive: true });
await page.goto('http://localhost:3200/RIND');
await page.getByRole('heading', { name: /Good work starts/ }).waitFor();
assert.equal(await page.locator('iframe').count(), 0);
await page.screenshot({ path: `${out}/rind-desktop.png`, fullPage: true });
await page.getByRole('button', { name: /Build something/ }).click();
await page.getByText('Sample run complete', { exact: true }).waitFor({ timeout: 15000 });
await page.getByRole('button', { name: /Review proposed change/ }).click();
await page.getByRole('heading', { name: 'Navigation active state' }).waitFor();
await page.screenshot({ path: `${out}/rind-result.png`, fullPage: true });
await page.getByRole('button', { name: 'Close inspector' }).click();
if (!(await page.getByRole('button', { name: /New session/ }).isVisible())) await page.getByRole('button', { name: 'Toggle sessions' }).click();
await page.getByRole('button', { name: /New session/ }).click();
await page.getByRole('button', { name: /Review a change/ }).click();
await page.getByRole('button', { name: /Continue review/ }).waitFor({ timeout: 10000 });
await page.getByRole('button', { name: /Continue review/ }).click();
await page.getByText('Sample run complete', { exact: true }).waitFor({ timeout: 15000 });
await page.getByRole('button', { name: /New session/ }).click();
await page.getByRole('button', { name: /Investigate an issue/ }).click();
await page.getByRole('button', { name: /Retry sample/ }).waitFor({ timeout: 10000 });
await page.getByRole('button', { name: /Retry sample/ }).click();
await page.getByText('Sample run complete', { exact: true }).waitFor({ timeout: 10000 });
await page.getByLabel('Describe a task').fill('Try a follow-up');
await page.getByRole('button', { name: 'Send', exact: true }).click();
await page.getByRole('button', { name: /Stop/, exact: false }).click();
await page.getByRole('heading', { name: 'Run stopped' }).waitFor();
await page.getByRole('button', { name: 'Expand workspace', exact: true }).click();
assert.equal(await page.locator('body > header').evaluate(el => el.inert), true);
await page.keyboard.press('Escape');
assert.equal(await page.locator('body > header').evaluate(el => el.inert), false);
await page.setViewportSize({ width: 390, height: 844 });
await page.reload();
await page.getByRole('heading', { name: /Good work starts/ }).waitFor();
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
await page.screenshot({ path: `${out}/rind-mobile.png`, fullPage: true });
await page.getByRole('button', { name: /Build something/ }).click();
await page.getByText('Sample run complete', { exact: true }).waitFor({ timeout: 15000 });
await page.getByRole('button', { name: /Review proposed change/ }).click();
await page.getByRole('heading', { name: 'Navigation active state' }).waitFor();
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
await page.screenshot({ path: `${out}/rind-mobile-inspector.png`, fullPage: true });
await page.getByRole('button', { name: 'Close inspector' }).click();
await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'dark'));
await page.screenshot({ path: `${out}/rind-dark.png`, fullPage: true });
assert.deepEqual(errors, []);
console.log('PASS: no iframe; completion, diff, input, failure/retry, follow-up, stop, expansion, mobile overflow, and runtime error checks.');
await browser.close();

